server:
  port: 8080
spring:
  application:
    name: "producerbridgestream"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

#-----------
# Spring cloud stream
  cloud:
    stream:
       bindings:
         output:                                  # Corresponde al nombre usado en StreamBridge
            destination: event.test.notification  # Corresponde al nombre del topico en kafka. En Rabbit al exchange
            binder: kafka                       # binder al cual se enlaza
            content-type: application/json

#------

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

